name: ci-cd

on:
  pull_request:
  push:
    branches:
      - qc

permissions:
  contents: read

jobs:
  pint:
    name: Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, pdo_pgsql, redis
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Pint
        run: vendor/bin/pint --test
